name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_NAME: Umbra.AetherFM.sln
      RELEASE_DIR: Umbra.AetherFM/out/Release
      RELEASE_NAME: Umbra.AetherFM
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Verify required DLLs
        shell: pwsh
        run: |
          Write-Host "Checking for required DLL files in lib directory..."
          $requiredDlls = @("Umbra.dll", "Umbra.Common.dll", "Una.Drawing.dll")
          $missingDlls = @()
          
          foreach ($dll in $requiredDlls) {
            if (Test-Path "lib\$dll") {
              Write-Host "✓ Found $dll"
            } else {
              Write-Host "✗ Missing $dll"
              $missingDlls += $dll
            }
          }
          
          if ($missingDlls.Count -gt 0) {
            Write-Error "Missing required DLL files: $($missingDlls -join ', ')"
            Write-Host "Please ensure all required DLL files are present in the lib/ directory before building."
            Write-Host "Required files: Umbra.dll, Umbra.Common.dll, Una.Drawing.dll"
            exit 1
          }
          
          Write-Host "All required DLL files are present. Proceeding with build..."
      
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_NAME }}
      - name: Build Release
        run: dotnet build ${{ env.SOLUTION_NAME }} -c Release --no-restore
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_NAME }}
          path: ${{ env.RELEASE_DIR }}/*


